# Generated by Django 4.1.7 on 2023-06-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('Specialist_doctor', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('address_detail', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Waiting_time', models.TimeField(blank=True, null=True)),
                ('working_hours', models.IntegerField(default=0)),
                ('number_phone', models.CharField(max_length=12)),
            ],
        ),
    ]
