# Generated by Django 4.1.7 on 2023-06-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_doctor_data_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_data',
            name='doctor_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor_data',
            name='doctor_service',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
