# Generated by Django 4.1.7 on 2023-06-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_doctor_data_doctor_info_doctor_data_doctor_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_writer_name', models.CharField(max_length=200)),
                ('comment_writer_email', models.CharField(max_length=500)),
                ('comment_message', models.TextField()),
            ],
        ),
    ]
