# Generated by Django 4.1.7 on 2023-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_posts_post_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone_number', models.CharField(max_length=12)),
                ('day_want', models.CharField(max_length=100)),
            ],
        ),
    ]
