# Generated by Django 4.1.7 on 2023-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_appoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_description', models.TextField(max_length=200)),
                ('publish_day', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('publish_time', models.TimeField()),
            ],
        ),
    ]
