# Generated by Django 4.2.3 on 2023-07-22 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_blogs_blog_image_doctor_data_clininc_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_data',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor_data',
            name='clininc_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
